In [12]:
import torch

In [13]:
torch.__version__

'2.5.1+cpu'

In [14]:
#scalar 
scalar= torch.tensor(6)
scalar , scalar.ndim

(tensor(6), 0)

In [15]:
#how to create a vector tensors ?
vector = torch.tensor([7,7])
vector ,vector.ndim

(tensor([7, 7]), 1)

In [16]:
#matrix 

matrix= torch.tensor([[1,5,6], [1,6,7]])
matrix ,matrix.ndim , matrix.shape

(tensor([[1, 5, 6],
         [1, 6, 7]]),
 2,
 torch.Size([2, 3]))

In [17]:
d3_tensor = torch.tensor([[[1,5,6], [1,6,7], [1,6,7]]])
d3_tensor , d3_tensor.ndim , d3_tensor.shape

(tensor([[[1, 5, 6],
          [1, 6, 7],
          [1, 6, 7]]]),
 3,
 torch.Size([1, 3, 3]))

In [23]:
#create a random tensor with rand 
random_tensor = torch.rand(size=(4,3))
random_tensor2 =torch.rand(d3_tensor.shape)

random_tensor2 , random_tensor ,random_tensor.shape

(tensor([[[0.7294, 0.7005, 0.1663],
          [0.0040, 0.7707, 0.0132],
          [0.3049, 0.8304, 0.1070]]]),
 tensor([[0.6313, 0.8768, 0.5003],
         [0.8652, 0.5007, 0.5299],
         [0.1670, 0.3404, 0.4275],
         [0.9633, 0.2272, 0.9401]]),
 torch.Size([4, 3]))

In [9]:
# check the shape of the random_tensor

random_tensor2.shape ,random_tensor.shape

(torch.Size([1, 3, 3]), torch.Size([4, 3]))

cuda = Gpu  


In [12]:
t_tenor=torch.tensor(data=[1,2,3,4,5],
                     dtype=torch.float32,
                     device='cpu',
                     requires_grad=False
                     )

t_tenor,t_tenor.dtype ,t_tenor.device

(tensor([1., 2., 3., 4., 5.]), torch.float32, device(type='cpu'))

# tensor  operations
1. multiplication
2. addition
3. subtraction
4. division


In [14]:
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [15]:
x= x +10 
x

tensor([11, 12, 13])

In [17]:
x = x - 2
x

tensor([7, 8, 9])

In [18]:
x = x *2
x

tensor([14, 16, 18])

In [19]:
x = x /2 
x

tensor([7., 8., 9.])

In [20]:
y = x * x
y

tensor([49., 64., 81.])

use a function multiply()

In [23]:
y = torch.multiply(x,10)
x , y

(tensor([700., 800., 900.]), tensor([7000., 8000., 9000.]))

use the funtion matmul to multiply the matrixs 

In [24]:
z = torch.tensor([1,2,3])
z=torch.matmul(z,z)
z ,  z.dtype , z.ndim

(tensor(14), torch.int64, 0)

In [26]:
tensor_a = torch.rand(size=(2,3))
tensor_a.shape , tensor_a

(torch.Size([2, 3]),
 tensor([[0.9047, 0.2004, 0.4753],
         [0.8317, 0.7770, 0.9596]]))

In [34]:
tensor_b = torch.rand(size=(3,4))
tensor_b

tensor([[0.9932, 0.0346, 0.4701, 0.0152],
        [0.3124, 0.8475, 0.8816, 0.3457],
        [0.7876, 0.5306, 0.2075, 0.1770]])

In [35]:
z = torch.matmul(tensor_a,tensor_b)
z

tensor([[1.3355, 0.4534, 0.7006, 0.1672],
        [1.8245, 1.1964, 1.2750, 0.4511]])

In [40]:
# manual seed generation to fix random funciton 
torch.manual_seed(43)

random_tensor = torch.rand(size=(3,2))
random_tensor

tensor([[0.4540, 0.1965],
        [0.9210, 0.3462],
        [0.1481, 0.0858]])

In [43]:
from torch import nn 

In [47]:
linear_layer = nn.Linear(in_features=6, out_features=4)
 
tensor_L= torch.rand(4,6)
x=linear_layer(tensor_L)
x

tensor([[-0.2179,  0.0555, -0.1415, -0.3343],
        [-0.7067,  0.1240,  0.0156, -0.4899],
        [-0.9055,  0.0031,  0.0145, -0.5833],
        [-0.7625,  0.1695,  0.1923, -0.4854]], grad_fn=<AddmmBackward0>)

In [53]:
v = torch.arange(0,16,2)
v

tensor([ 0,  2,  4,  6,  8, 10, 12, 14])

In [54]:
v.min(),v.max(),

(tensor(0), tensor(14))

In [56]:
max_index= v.argmax()
max_index

tensor(7)

In [57]:
min_index= v.argmin()
min_index

tensor(0)

In [50]:
#permute
i= torch.rand(224,224,3)
i,i.shape

(tensor([[[0.7314, 0.1676, 0.7472],
          [0.4296, 0.2978, 1.0000],
          [0.1835, 0.3448, 0.1852],
          ...,
          [0.7771, 0.4264, 0.5789],
          [0.3216, 0.1163, 0.7913],
          [0.1016, 0.1612, 0.8269]],
 
         [[0.3010, 0.0412, 0.6285],
          [0.0090, 0.9737, 0.7490],
          [0.6115, 0.0127, 0.5286],
          ...,
          [0.1438, 0.9422, 0.0873],
          [0.5380, 0.6891, 0.6147],
          [0.9233, 0.7026, 0.1143]],
 
         [[0.8074, 0.7851, 0.8026],
          [0.2290, 0.5250, 0.0056],
          [0.7525, 0.2202, 0.4270],
          ...,
          [0.0436, 0.8914, 0.3851],
          [0.8518, 0.1138, 0.6273],
          [0.6362, 0.5181, 0.3245]],
 
         ...,
 
         [[0.1350, 0.1791, 0.3272],
          [0.8661, 0.1079, 0.1977],
          [0.8971, 0.3544, 0.5970],
          ...,
          [0.5281, 0.4045, 0.5605],
          [0.4093, 0.1733, 0.9741],
          [0.4265, 0.9243, 0.2073]],
 
         [[0.1369, 0.2414, 0.1874],
          [0

In [51]:
i_permute=torch.permute(i,(2,0,1))
i_permute.shape

torch.Size([3, 224, 224])

In [52]:
x=torch.rand(2,2,3)
x

tensor([[[0.7504, 0.3162, 0.9962],
         [0.3430, 0.8787, 0.4968]],

        [[0.1366, 0.7020, 0.8155],
         [0.3354, 0.7320, 0.8777]]])

In [54]:
x[1][0][1]

tensor(0.7020)

In [55]:
import numpy as np 

In [61]:
r=np.arange(2,10,2)
r,r.dtype ,type(r)

(array([2, 4, 6, 8]), dtype('int32'), numpy.ndarray)

In [62]:
#transform array to tensor
r_tensor = torch.from_numpy(r) 
type(r_tensor)

torch.Tensor

In [63]:
x= torch.arange(0,10,2)
x , type(x)


(tensor([0, 2, 4, 6, 8]), torch.Tensor)

In [64]:
# transform tensor to array
x_numpy=x.numpy()
type(x_numpy)

numpy.ndarray

In [69]:
#set the manual seed 
torch.manual_seed(500)
random_tensor=torch.rand(2,2,1)
random_tensor

tensor([[[0.5820],
         [0.1338]],

        [[0.7995],
         [0.3071]]])

In [71]:
#Gpu
!nvidia-smi

Mon Jan 27 17:33:50 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 561.19                 Driver Version: 561.19         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce MX350         WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   54C    P0             N/A /   20W |       0MiB /   2048MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [72]:
#check if the device supports GPU or cpu 
device= 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [73]:
devices= 'many' if torch.cuda.device_count() else 'noOne'
devices

'noOne'

In [74]:
tensor= torch.tensor([2,5])
tensor , tensor.device 

(tensor([2, 5]), device(type='cpu'))

In [ ]:
#to change the tensor from the cpu to gpu
tensor_gpu= torch.tensor.to('cuda') 

In [77]:
x_train=tensor.to(device)
x_train.device

device(type='cpu')

In [88]:
cpu_tensor=x_train.cpu().numpy()
type(cpu_tensor)

numpy.ndarray